### PR TITLE
Accenture tenant migration

### LINKED ISSUE #32: Use AWS secret manager to manage passwords
Problem:
Currently, we are using ansible-vault to encrypt password file and this file can be find in the Github repository.

Resolution:
If we use AWS Secret manager, we could get the password dynamically in the task definition and it will not appear in the AWS tenant when listing information about the task.

Status:
Need to be implemented.

### LINKED ISSUE #54: Migration into the Accenture tenant
Due to internal restriction, we will need to move the current tenant into an other one.

Estimation point: 5

### PR DESCRIPTION
**Pull request by aboulay**
Current status of the migration:

- [x] 00_ecs_cluster
- [x] 00_network
- [x] 00_lambda_snapshot_bucket
- [x] 00_lambda_metrics_bucket
- [x] 01_rds_cluster
- [x] 01_snapshot_bucket
- [x] 01_frontend
- [x] 01_lambda_snapshot_carthagenet
- [x] 01_lambda_snapshot_mainnet
- [x] 01_tezos_mainnet_rolling_node
- [x] 01_tezos_mainnet_archive_node
- [x] 01_tezos_carthagenet_rolling_node
- [x] 01_tezos_carthagenet_archive_node
- [x] 02_lambda_metrics
- [x] 02_service_api
- [x] 02_service_proxy_carthagenet
- [x] 02_service_proxy_mannet

### CODE REVIEW

**Comment by aboulay** [comment]
WFD on https://github.com/octo-technology/tezos-link/pull/112

**Comment by louptheron** [comment]
@aboulay Can I merge ? no issue left ? (just asking because the PR is pretty large)

**Comment by aboulay** [comment]
@louptheron I dont know what are you talking about. :trollface:  (Yes, you can)

Just have a look to the lambdas' code which change a bit due to new format secret system and ACP compliance.

For terraform part, normally it should be better. I have refactor it to be more DRY than before. It works so don't worry about it.

**Comment by aboulay** [comment]
It will resolve the secret management bonus and the accenture tenant migration. In the project board :)

**Review by louptheron — APPROVED** [review]

**Pull request merged**
